# Workflow for running pytest on commit.

name: Python package

# runs on pull and push in the master branch:
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build":
  build:
    # The type of runner that the job will run on:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # steps executed by jobs:
    steps:
      - uses: actions/checkout@v2

      # sets up python environment:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # installs dependencies:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # runs pytest:
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test_calculator.py
